[project]
name = "training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.4.1",
    "mlflow>=3.9.0",
    "modal>=1.3.3",
    "rouge-score>=0.1.2",
    "seaborn>=0.13.2",
]
